"""
tools.py — Tool definitions and dispatcher for the Medical Assistant agent.

EDUCATIONAL DISCLAIMER: These tools support an educational symptom-assessment
workflow only. They do not provide medical diagnoses or professional medical advice.
"""

import json
from datetime import datetime


# ── Urgency calculation ────────────────────────────────────────────────────────

def calculate_urgency(score: int) -> dict:
    """
    Convert a numeric urgency score (1–100) into a human-readable triage level.

    Args:
        score: Integer between 1 and 100 representing symptom urgency.

    Returns:
        dict with keys: score, level, label, recommendation, disclaimer
    """
    score = max(1, min(100, int(score)))  # clamp to [1, 100]

    if score <= 25:
        level = "LOW"
        label = "Low Urgency"
        recommendation = (
            "Your symptoms appear mild. Consider self-care measures such as rest, "
            "hydration, and over-the-counter remedies if appropriate. Monitor your "
            "symptoms and contact a healthcare provider if they worsen or persist "
            "beyond a few days."
        )
    elif score <= 50:
        level = "MEDIUM"
        label = "Medium Urgency"
        recommendation = (
            "Your symptoms warrant medical attention but are not immediately life-threatening. "
            "Schedule an appointment with your primary care provider within 1–3 days. "
            "If symptoms worsen significantly before then, seek urgent care."
        )
    elif score <= 75:
        level = "HIGH"
        label = "High Urgency"
        recommendation = (
            "Your symptoms suggest you should be evaluated today. Please visit an urgent "
            "care clinic or contact your doctor for a same-day appointment. Do not wait "
            "if symptoms are getting worse."
        )
    else:
        level = "EMERGENCY"
        label = "EMERGENCY — Seek Immediate Care"
        recommendation = (
            "⚠️  CALL 911 or go to the nearest Emergency Room IMMEDIATELY. "
            "Your symptoms may indicate a serious or life-threatening condition "
            "that requires immediate professional medical attention. Do not drive yourself."
        )

    return {
        "score": score,
        "level": level,
        "label": label,
        "recommendation": recommendation,
        "disclaimer": (
            "EDUCATIONAL DISCLAIMER: This urgency level is generated by an AI tool "
            "for educational purposes only and does not constitute medical advice or "
            "a clinical triage assessment. Always consult a qualified healthcare "
            "professional for medical concerns."
        ),
    }


# ── Report generation ──────────────────────────────────────────────────────────

def generate_report(
    primary_symptom: str,
    symptom_duration: str,
    severity_score: int,
    associated_symptoms: list[str],
    red_flags_present: list[str],
    urgency_level: str,
    urgency_score: int,
    recommendation: str,
    age_group: str = "Not specified",
    relevant_history: str = "None reported",
    additional_notes: str = "",
) -> dict:
    """
    Assemble a structured JSON triage report from collected assessment data.

    Returns:
        dict representing the full triage report.
    """
    report = {
        "report_metadata": {
            "tool": "Medical Assistant — Educational Symptom Assessment",
            "generated_at": datetime.utcnow().isoformat() + "Z",
            "disclaimer": (
                "THIS REPORT IS FOR EDUCATIONAL PURPOSES ONLY. It does not constitute "
                "medical advice, a clinical diagnosis, or a substitute for evaluation by "
                "a licensed healthcare professional. In an emergency, call 911 immediately."
            ),
        },
        "patient_summary": {
            "age_group": age_group,
            "relevant_medical_history": relevant_history,
        },
        "symptom_assessment": {
            "primary_symptom": primary_symptom,
            "duration": symptom_duration,
            "self_reported_severity": f"{severity_score}/10",
            "associated_symptoms": associated_symptoms,
            "red_flags_identified": red_flags_present if red_flags_present else ["None identified"],
        },
        "triage_result": {
            "urgency_score": urgency_score,
            "urgency_level": urgency_level,
            "recommendation": recommendation,
        },
        "additional_notes": additional_notes or "None",
        "follow_up_reminders": [
            "Keep track of any new or worsening symptoms.",
            "Bring this report summary to your healthcare provider if helpful.",
            "This assessment does not replace a clinical examination.",
        ],
    }
    return report


# ── Tool definitions for the Anthropic API ────────────────────────────────────

TOOL_DEFINITIONS = [
    {
        "name": "calculate_urgency",
        "description": (
            "Calculate a triage urgency level from a numeric score (1–100). "
            "Use this after gathering sufficient symptom information. "
            "Score 1–25 = LOW, 26–50 = MEDIUM, 51–75 = HIGH, 76–100 = EMERGENCY."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "score": {
                    "type": "integer",
                    "description": "Urgency score from 1 (very mild) to 100 (life-threatening emergency).",
                    "minimum": 1,
                    "maximum": 100,
                }
            },
            "required": ["score"],
        },
    },
    {
        "name": "generate_report",
        "description": (
            "Assemble a structured JSON triage report after urgency has been calculated. "
            "Call this once you have collected all symptom details and have an urgency level."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "primary_symptom": {
                    "type": "string",
                    "description": "The main symptom or complaint the user reported.",
                },
                "symptom_duration": {
                    "type": "string",
                    "description": "How long the symptom has been present (e.g., '2 days', '3 hours').",
                },
                "severity_score": {
                    "type": "integer",
                    "description": "User's self-reported severity on a 1–10 scale.",
                    "minimum": 1,
                    "maximum": 10,
                },
                "associated_symptoms": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "List of additional symptoms reported (e.g., ['fever', 'nausea']).",
                },
                "red_flags_present": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "List of red-flag symptoms identified, or empty list if none.",
                },
                "urgency_level": {
                    "type": "string",
                    "enum": ["LOW", "MEDIUM", "HIGH", "EMERGENCY"],
                    "description": "The urgency level returned by calculate_urgency.",
                },
                "urgency_score": {
                    "type": "integer",
                    "description": "The numeric urgency score used.",
                },
                "recommendation": {
                    "type": "string",
                    "description": "The recommendation text from calculate_urgency.",
                },
                "age_group": {
                    "type": "string",
                    "description": "Patient age group: child, adult, or elderly.",
                    "default": "Not specified",
                },
                "relevant_history": {
                    "type": "string",
                    "description": "Brief relevant medical history or 'None reported'.",
                    "default": "None reported",
                },
                "additional_notes": {
                    "type": "string",
                    "description": "Any other relevant notes from the assessment.",
                    "default": "",
                },
            },
            "required": [
                "primary_symptom",
                "symptom_duration",
                "severity_score",
                "associated_symptoms",
                "red_flags_present",
                "urgency_level",
                "urgency_score",
                "recommendation",
            ],
        },
    },
]


# ── Tool dispatcher ────────────────────────────────────────────────────────────

def run_tool(tool_name: str, tool_input: dict) -> str:
    """
    Dispatch a tool call by name and return the result as a JSON string.

    Args:
        tool_name:  Name of the tool to run.
        tool_input: Dictionary of arguments from the model.

    Returns:
        JSON-encoded string of the tool result.
    """
    if tool_name == "calculate_urgency":
        result = calculate_urgency(score=tool_input["score"])
    elif tool_name == "generate_report":
        result = generate_report(**tool_input)
    else:
        result = {"error": f"Unknown tool: {tool_name}"}

    return json.dumps(result, indent=2)
